### PR TITLE
Updated markdown

### PR DESCRIPTION
**Pull request by Razican**
Updated markdown parser version.

### CODE REVIEW

**Comment by waynenilsen** [comment]
Can you also bump minor version?

**Comment by Razican** [comment]
Done ;)

**Comment by waynenilsen** [comment]
That's actually [patch](http://semver.org/) number, can you bump minor? (the second number) not to be a pain, thanks for doing this maintenance work :+1:

**Comment by Razican** [comment]
Yes, sorry, I misunderstood. Fixed and squashed commits :)

**Comment by Razican** [comment]
I rebased the changes from the handlebars update, now it can easily be merged :)

**Comment by waynenilsen** [comment]
All that is left now is to publish, thanks again

**Comment by waynenilsen** [comment]
@Razican published

**Comment by Razican** [comment]
Thanks!

**Pull request merged**
