### PR TITLE
Update handlebars helper to 0.24+ API

### PR DESCRIPTION
**Pull request by sunng87**
I had some breaking change early this year. And https://github.com/sunng87/handlebars-rust/issues/154 may have compatibility issue.

### CODE REVIEW

**Comment by sunng87** [comment]
I'm using rustfmt so there might be some unrelated formation change. Hope you don't mind 🤣

**Comment by waynenilsen** [comment]
I really like rustfmt and have wanted to start using it. I will accept this PR when I can get to my terminal and `cargo publish` it. I may add a rustfmt config file and re-format because I prefer block indent over visual. Thank you very much for keeping my crate up to date :+1:

**Comment by sunng87** [comment]
@waynenilsen Thank you!

**Comment by waynenilsen** [comment]
Thanks for the pr, you're in. https://crates.io/crates/handlebars-markdown-helper 👍

**Pull request merged**
